
# Node version
FROM node:18

# Make work directory
WORKDIR /usr/src/app

# Copy files
COPY package*.json ./
COPY tsconfig.json ./
COPY . ./

# Install & build
RUN npm install --legacy-peer-deps

# PORT defined
EXPOSE 3000

# Set ENV variables
ENV REACT_APP_BACKEND_URL={REACT_APP_BACKEND_URL}
ENV REACT_APP_CLIENT_ID={REACT_APP_CLIENT_ID}
ENV REACT_APP_APIKEY={REACT_APP_APIKEY}
ENV REACT_APP_AUTHDOMAIN={REACT_APP_AUTHDOMAIN}
ENV REACT_APP_PROJECTID={REACT_APP_PROJECTID}
ENV REACT_APP_STORAGEBUCKET={REACT_APP_STORAGEBUCKET}
ENV REACT_APP_MESSAGINGSENDERID={REACT_APP_MESSAGINGSENDERID}
ENV REACT_APP_APPID={REACT_APP_APPID}

# Execute command
CMD [ "npm", "start"]