version: "3.9"

services:
  frontend:
    build: ./
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL={REACT_APP_BACKEND_URL}
      - REACT_APP_CLIENT_ID={REACT_APP_CLIENT_ID}
      - REACT_APP_APIKEY={REACT_APP_APIKEY}
      - REACT_APP_AUTHDOMAIN={REACT_APP_AUTHDOMAIN}
      - REACT_APP_PROJECTID={REACT_APP_PROJECTID}
      - REACT_APP_STORAGEBUCKET={REACT_APP_STORAGEBUCKET}
      - REACT_APP_MESSAGINGSENDERID={REACT_APP_MESSAGINGSENDERID}
      - REACT_APP_APPID={REACT_APP_APPID}
